# | CustomJoinAndQuitMessage |
# |   By jonagamerpro1234    |
# |      Version 1.7.0       |
# |__________________________|
# 
# There are two variables that show the name of the player in a message and that are | <Name>, <DisplayName> | these two variables can also be in lowercase.
#
Config:

  # |Lang| you can use the available languages of the plugin or you can add your own translations [ Default = en-US ]
  Lang: en-US 
  
  # |Update| This function lets you know if there is a plugin update [Does not disable console messages]
  Update: true
  
  # |Debug| shows you important information about the plugin loading 
  Debug: false
  
  # |Type|  the type is a way of knowing what is being used whether in the [ normal ] or [ group ] format
  Type: normal
    
#
# | Join |
# 
Join:
  
  # |Text| This is where Join customizable message is located
  Text: '&b[&a+&b] <name>'
  
  # |Type|
  Type: normal
  
  HoverEvent:
    
    # |Enabled| Here you can enable or disable this feature
    Enabled: true
  
    Hover: 
      - '&6hello &b<name>'

  ClickEvent:
    
    # |Enabled| Here you can enable or disable this feature
    Enabled: true
    
    Mode: command
    
    Actions:
      
      Command: 'tell <name> hello player'
      
      Url: ''
      
      Suggest-Command: '/msg <name>'
  
  Sound:
    
    # |Enabled| Here you can enable or disable this feature
    Enabled: true
    
    Sound: 'BLOCK_NOTE_BLOCK_PLING'
    
    Pitch: 1
    
    Volume: 10
    
    
  Title:
    
    # |Enabled| Here you can enable or disable this feature
    Enabled: true
    
    Title: ''
    
    SubTitle: ''
    
    FadeIn: 20
    
    Stay: 40
    
    FadeOut: 20
  
  ActionBar:
    
    # |Enabled| Here you can enable or disable this feature
    Enabled: true
    
    Text: ''
  
Quit:
  Enabled: true
  Text: '&b[&c-&b] <name>' #|<name>, <displayname> |
# |Type|
# |> [ Custom | Double | Hover | Click | None | Group ]
  Type: Custom
  Hover:
    Text: 
      - '&6bay &c<name>'
# |Mode| 
# |> [TEXT] show hover text
    Mode: TEXT 
# |Legacy-Color| 
# |> the legacy color mode is used to activate the old color system for hover event 
# |> legay color does not need to use the color format, for example [ &6 ]
# |> Colors [RED] | [AQUA] | [BLUE] | [GREED] | [GOlD] | ....etc
    Legacy-Color: false  
    Color: AQUA 
  Click:
    Action: 'say hello'
# |Mode| 
# |> [URL] open a link 
# |> [CMD] run a command
    Mode: CMD 
#
# |Welcome| 
# Here you can customize the welcome message for players when entering the server
# | Vars | there are variables that only work in certain functions
#  <0> leave an empty line
Welcome:
# |Enabled| turn the welcome message on and off [ Default | true ]
  Enabled: true
# |Max Line| is the maximum number of lines allowed to avoid a bug [Default | 8] 
  Max-Line: 8 
  Text:
    - '&b&m=========================================&r'
    - '<0>'
    - '&e> &7Welcome To The Server &b<name>'
    - '<0>'
    - '&e> &cShop: shop-example.com'
    - '&e> &7Use &b/skin to put on a skin'
    - '<0>'
    - '&b&m=========================================&r'
#
# |Title|
# |> Here you can customize the title for the players when entering the server for more help with the ticks, enter this link
# |> https://github.com/jonagamerpro1234/MultiOptions/wiki/Ticks-in-Minecraft 
Title:
  Enabled: true #|Enabled| here you can activate and deactivate the title in this option [Default | true]
  Text:
    Title: '&a&lWelcome to the server'
    SubTitle: '&b<name>'
  Settings:
    Time:
      FadeIn: 20 #| Default 20 ticks | 20 ticks = 1s
      Stay: 40 #| Default 40 ticks | 40 ticks = 2s
      FadeOut: 20 #| Default 20 ticks | 20 ticks = 1s
#
# |Actionbar|
# |> Here you can customize the Actionbar for the players when entering the server
Actionbar:
  Enabled: true #|Enabled| here you can activate and deactivate the actionbar in this option [Default | true]
  Text: 'Welcome to the server <name>'
#
# |Sounds|
#
# Format: <sound name>;<vol>;<pitch>        
# Ej 1.9.  BLOCK_NOTE_PLING;10;2      
# Sound list: https://www.spigotmc.org/wiki/cc-sounds-list/ 
Sounds:
  Enabled: true
  Type: Normal #| Normal | Group |
  Settings:
    Send-All-Sounds: true
  Join:
    Enabled: true
    Sound: BLOCK_NOTE_PLING;10;1
    Enabled-Permission: false
    Custom-Permission: 'Cjm.join'
  Quit:
    Enabled: true
    Sound: BLOCK_NOTE_PLING;10;1
    Enabled-Permission: false
    Custom-Permission: 'Cjm.quit'
#  
# |Groups|
# |> currently only join and quit functions are available for the group system
# |> to be able to use the group system properly it is necessary to have a permissions plugin with [LuckPerm or others]
#
# |Groups:
# |  <group name>:
# |    Join:
# |      Text: 'hello'
# |      Permission: 'my.permission'
# |      Enabled-Sound: true
# |      Sound: <sound name>;<vol>;<pitch>
# |      Send-All-Sound: true
# |    Quit:
# |      Text: 'hello'
# |      Permission: 'my.permission'
# |      Enabled-Sound: true
# |      Sound: <sound name>;<vol>;<pitch>
# |      Send-All-Sound: true  
Groups:
  Default:
    Join:
      Text: '&6[&a+&6] &7<name>'
      Permission: 'cjm.group.join.default'
      Enabled-Sound: true
      Sound: BLOCK_NOTE_PLING;10;1
      Send-All-Sound: true
    Quit:
      Text: '&6[&c-&6] &7<name>'
      Permission: 'cjm.group.quit.default'
      Enabled-Sound: true
      Sound: BLOCK_NOTE_PLING;10;1
      Send-All-Sound: true
  Vip:
    Join:
      Text: '&6[&a+&6] &eWelcome to server &a[&b<name>&a]'
      Permission: 'cjm.group.join.vip'
      Enabled-Sound: true
      Sound: BLOCK_NOTE_PLING;10;1
      Send-All-Sound: true
    Quit:
      Text: '&6[&c-&6] &eSee you soon &a[&b<name>&a]'
      Permission: 'cjm.group.quit.vip'
      Enabled-Sound: true
      Sound: BLOCK_NOTE_PLING;10;1
      Send-All-Sound: true
  Admin:
    Join:
      Text: '&bThe admin &6[&c<name>&6] &bjoined the server'
      Permission: 'cjm.group.join.admin'
      Enabled-Sound: true
      Sound: BLOCK_NOTE_PLING;10;1
      Send-All-Sound: true
    Quit:
      Text: 'The admin [<name>] quit of server'
      Permission: 'cjm.group.quit.admin'
      Enabled-Sound: true
      Sound: BLOCK_NOTE_PLING;10;1
      Send-All-Sound: true
#
# |> This is the end of the configuration ... [-_-] more things coming soon
# 
# | Config File  |
# | Version 1.7  |
#