#    ______    _____   ____    __  ___
#   / ____/   / /   | / __ \  /  |/  /
#  / /   __  / / /| |/ / / / / /|_/ /  By jonagamerpro1234
# / /___/ /_/ / ___ / /_/ / / /  / /   Version ${project.version}
# \____/\____/_/  |_\___\_\/_/  /_/    Thanks for using CustomJoinAndQuitMessage <3
#
# ● A simple plugin for personalization of the join and quit messages and more...
#
# ● Spigot: https://www.spigotmc.org/resources/custom-join-and-quit-message-1-8-x-1-19-x.57006/
# ● Discord: https://discord.gg/c5GhQDQCK5
# ● Issue Tracker: https://github.com/jonagamerpro1234/CustomJoinAndQuitMessages/issues
# ● Plugin Statistics: https://bstats.org/plugin/bukkit/CustomJoinAndQuitMessages/6318

# | Settings |
Settings:

  # Shows you important information about the plugin loading
  Debug: true

  # You can use the available languages of the plugin, or you can add your own translations [ Default = en_US ]
  Lang: en_US

  # This function lets you know if there is a plugin update [Does not disable console messages]
  Update:

    # Here you can enable or disable this feature
    Enabled: true

    # You will get the updates from [spigot | github] what is the difference, here below is the explanation of why
    # |Spigot| Get only released updates, and you won't receive beta notifications
    # |Modrinth| ---
    # |GitHub| Get only the released and beta updates, and you will be able to receive notifications of both versions
    GetFromUpdate: spigot

# | Hooks |
Hooks:

  # Here you can configure everything related to LuckPerms and or deactivate or activate functions
  LuckPerms:

    # Here you can enable or disable this feature
    Enabled: true

    # This function allows the plugin to detect if the player has changed rank in a period of time defined in the [Tick] section
    AutoUpdateGroup:

      # Here you can enable or disable this feature
      Enabled: true

      # Here you can define the time that the actions are automatically executed [Default = 600], 600 tick = 30 sec
      Tick: 600

  # Here you can define the discord channel where the messages from minecraft to discord are seen
  DiscordSVR:

    # Here you can enable or disable this feature
    Enabled: true

    # Here is the id of the channel that is used for the chat
    Channel-Id: "none"

  # Aqui podras cambiar los ajustes de cada implementacion que funciona con EssentialsX
  EssentialsX:

    Enabled: true

    # This allows you to join or quit the server without the message being shown to other players.
    HidePlayerIsVanish: true

    #
    DisableJoinQuitSoundsInVanish: true

    # Here you can define the discord channel where the messages from minecraft to discord are seen
    # (!) Es necesario tener el plugin de [ EssentialsDiscord ] para que funcione
    EssentialsDiscord:

      # Here you can enable or disable this feature
      Enabled: true

      # Here is the id of the channel that is used for the chat
      Channel-Id: "none"

      # Usara el canal que se encuentra definido en la configuracion del plugin EssentialsDiscord y ignorara el Channel-Id de CustomJoinAndMessages
      UseDefaultChannel: false

# | ChatFormat |
# Aqui pordras personalizar los mensajes de entrada y salida del jugador y tambien podras personalizar los mensajes con diversas funciones
# (!) Para personalizacion por grupos es necesario que cambie el tipo a [ group ]
ChatFormat:

  # Here you can enable or disable the chat to be seen in the console
  ShowChatInConsole: true

  # Aqui podras configurar el tipo del formato los cuales son
  # |normal| Sirve para la personalizacion general de todos los jugadores de los mensajes de entrada y salida, esto no permite usar las funciones de grupo
  # |group| Sirve para la personalizacion por grupos y desabilita la personalizacion general y permite una personalizacion mejor para cada grupo
  # (!) Es necesario tener LuckPerms para usar la personalizacion por grupos
  Type: normal

  # | Join |
  Join:

    # Here you can enable or disable this feature
    Enabled: true

    # Aqui puedes definir el mensaje de entra
    Format: "&e[&a+&e] &3{player} &7has joined the server"

    #
    JoinMessageDelay: 0

    #
    Title-Settings:

      # Here you can enable or disable this feature
      Enabled: true

      #
      Title: ""

      #
      SubTitle: ""

      #
      FadeIn: 20

      #
      Stay: 40

      #
      FadeOut: 20

    #
    Actionbar:

      # Here you can enable or disable this feature
      Enabled: true

      #
      Delay: 0

      #
      Format: ""

    Sound:

      # Here you can enable or disable this feature
      Enabled: true

      #
      SendToAll: true

      #
      Name: "BLOCK_NOTE_BLOCK_PLING"

      #
      Volume: 10

      #
      Pitch: 1

  # | First Join |
  First-Join:

    # Here you can enable or disable this feature
    Enabled: true

    #
    Format: "&3Welcome to the server, we hope you enjoy your time here and have a good time"

    #
    FirstJoinMessageDelay: 0

    #
    Title-Settings:

      # Here you can enable or disable this feature
      Enabled: true

      #
      Title: ""

      #
      SubTitle: ""

      #
      FadeIn: 20

      #
      Stay: 40

      #
      FadeOut: 20

    #
    Actionbar:

      # Here you can enable or disable this feature
      Enabled: true

      #
      Delay: 0

      #
      Format: ""

    #
    Sound:

      # Here you can enable or disable this feature
      Enabled: true

      #
      SendToAll: true

      #
      Name: "BLOCK_NOTE_BLOCK_PLING"

      #
      Volume: 10

      #
      Pitch: 1

  # | Quit |
  Quit:

    # Here you can enable or disable this feature
    Enabled: true

    # Aqui puedes definir el mensaje de salida
    Format: "&e[&c-&e] &3{player} &7has left the server"

    #
    Title-Settings:

      # Here you can enable or disable this feature
      Enabled: true

      #
      Title: ""

      #
      SubTitle: ""

      #
      FadeIn: 20

      #
      Stay: 40

      #
      FadeOut: 20

    #
    Actionbar:

      # Here you can enable or disable this feature
      Enabled: true

      #
      Delay: 0

      #
      Format: ""

    #
    Sound:

      # Here you can enable or disable this feature
      Enabled: true

      #
      SendToAll: true

      #
      Name: "BLOCK_NOTE_BLOCK_PLING"

      #
      Volume: 10

      #
      Pitch: 1

# |Welcome|
Welcome:

  # Here you can enable or disable this feature
  Enabled: true

  # Permite usa un mensaje de bienvenida por grupo y desactiva el mensaje general de bienvenida
  UseWelcomePerGroup: false

  #
  Delay: 0

  # Here you can set your own welcome message when entering
  Text:
    - '<gradien:#8200FC:#00FC95>&m=========================================</gradien>&r'
    - '<0>'
    - '&e> &7Welcome To The Server &b<name>'
    - '<0>'
    - '&e> <red>Shop: shop-example.com'
    - '&e> &7Use &b/skin to put on a skin'
    - '<0>'
    - '<gradien:#8200FC:#00FC95>&m=========================================</gradien>&r'

# I would not change anything
File-Version: 5

# |> This is the end of the configuration... [-_-] more things coming soon
#
# | Config File  |
# | Version 1.8  |
#